-- Migration: make the organization-documents (KYC) bucket private
-- Run in Supabase SQL Editor.
--
-- Context: registration certificates and PAN cards were stored with public URLs
-- (anyone with the link could read a PAN card). They're now served to admins
-- only, via short-lived signed URLs generated by the backend
-- (organization.service.ts -> getPendingOrganizations). Flipping the bucket to
-- private disables public URL access; signed URLs still work.
--
-- Uploads during org signup are unauthenticated (the org has no account yet) and
-- are governed by the existing storage RLS INSERT policy, which the `public`
-- flag does not affect — so signups keep working. This only removes public READ.

update storage.buckets
  set public = false
  where id = 'organization-documents';

-- Verify:
-- select id, public from storage.buckets where id = 'organization-documents';
-- (public should be false)
